[Interface]
PrivateKey = EItirRMB5tr2jrvnbhqFfkl2hj4S09PS9GnSZJ5R42k=
Address = 10.8.0.1/24
ListenPort = 51820

[Peer]
PublicKey = NTQN8mv09V1wT+UpzWXWMuckGDkbCRL/Rfzq/9OiHXA=
AllowedIPs = 10.8.0.2/32
